### ISSUE TITLE
При запуске теста shouldAddGame в классе GameStore в консоли выскакивает ошибка конструктора

### ISSUE THREAD

**Issue by PershikovaEP** [Megalapka/javaqa-team-diplom#1]
# Описание
При запуске теста shouldAddGame в классе GameStore в консоли выскакивает ошибка конструктора (java: constructor GameStore in class ru.netology.GameStore cannot be applied to given types;)

# Локация дефекта
https://github.com/Megalapka/javaqa-team-diplom/blob/a11cd75957fd77cf6c40e197392dfd0019eb99f2/src/test/java/ru/netology/GameStoreTest.java#L13-L20

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Megalapka/javaqa-team-diplom) в IDEA
1. Открыть класс GameStoreTest
1. Запустить тест shouldAddGame
1. Посмотреть в консоли

*Ожидаемый результат:* Тест пройден
*Фактический результат:* Вывод сообщения об ошибке: 
java: constructor GameStore in class ru.netology.GameStore cannot be applied to given types;
  required: no arguments
  found: java.util.Map<java.lang.String,java.lang.Integer>
  reason: actual and formal argument lists differ in length

# Скриншот
![image](https://user-images.githubusercontent.com/103420483/179287453-e3615282-fe7b-4b3e-bfb0-a1ecb5154b46.png)

# Окружение
* **Операционная система:** Windows 10 Домашняя
* **IDE:** IntelliJ IDEA Community Edition 2022.1.1
* **Java:** corretto-11.0.15

**Comment by Megalapka** [comment]
Issue#1 fixed, and fixed containsGame. Test shouldAddGame Passed
В GameStore внесла 2 конструктора. Исправила метод containsGame

**Comment by PershikovaEP** [comment]
В связи с ошибочным написанием теста этот баг не актуален. Конструктор добавлять не нужно.
