### ISSUE TITLE
Усовершенствование метода play для класса Player

### ISSUE THREAD

**Issue by Megalapka** [Megalapka/javaqa-team-diplom#14]
# Описание
Внести изменение в метод play для класса Player, чтоб убрать ветку, в которая никогда не произойдет

# Локация дефекта
https://github.com/Megalapka/javaqa-team-diplom/blob/30ed2c422788ea5c56049a876c87f6dcb99939ea/src/main/java/ru/netology/Player.java#L41-L53

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Megalapka/javaqa-team-diplom/blob/main/src/main/java/ru/netology/Player.java) в IDEA
1. Исправить метод play

# Окружение

* **Операционна система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA 2022.1.1 (Community Edition)
* **Java:** corretto-11

**Comment by PershikovaEP** [comment]
Нужна одобрительная рецензия. Не получается запушить, не хватает прав

**Comment by Megalapka** [comment]
Изменила настройки ветки main

**Comment by PershikovaEP** [comment]
Исправила метод play (коммит Change a method play in class Player)
