### ISSUE TITLE
Обнуляется сумма сыгранных игр по жанру

### ISSUE THREAD

**Issue by Megalapka** [Megalapka/javaqa-team-diplom#3]
# Описание
При суммировании нескольких игр по одному жанру, сумма в итоге обнуляется.

# Локация дефекта
https://github.com/Megalapka/javaqa-team-diplom/blob/bd18eb18a316c1a098ccc18185b6aede417ee3d0/src/main/java/ru/netology/Player.java#L45-L55

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Megalapka/javaqa-team-diplom/blob/main/src/test/java/ru/netology/PlayerTest.java) в IDEA
1. Запустить первый тест shouldSumGenre
1. Посмотреть в консоли

*Ожидаемый результат:* Тест пройден. Отображается общее время сыгранных игр по жанру "Genre1"
*Фактический результат:* Тест провален. Сумма обнулилась

# Скриншот
![issue3](https://user-images.githubusercontent.com/103579821/179306585-74dcf53c-217a-4f17-8a65-7c0e7db93e5e.jpg)

# Окружение

* **Операционна система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA 2022.1.1 (Community Edition)
* **Java:** corretto-11

**Comment by PershikovaEP** [comment]
Исправлен метод sumGenre в классе Player. Тест пройден - выполняется суммирование времени по жанру.
