### ISSUE TITLE
Время, в течение которого игрок играл в игру, не суммируется с прошлым временем

### ISSUE THREAD

**Issue by PershikovaEP** [Megalapka/javaqa-team-diplom#4]
# Описание
Количество времени, которое проиграл игрок за игрой этого каталога не суммируется с прошлым значением для этого игрока

# Локация дефекта
https://github.com/Megalapka/javaqa-team-diplom/blob/bd18eb18a316c1a098ccc18185b6aede417ee3d0/src/main/java/ru/netology/GameStore.java#L46-L52

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Megalapka/javaqa-team-diplom) в IDEA
1. Открыть класс GameStoreTest
1. Запустить тест shouldRegisterTimeWhenPlayerPlayGame
1. Посмотреть в консоли

*Ожидаемый результат:* Тест пройден. Время, в течение которого игрок играл в игру, суммируется с прошлым временем.
*Фактический результат:* Тест не пройден. Время, в течение которого игрок играл в игру, не суммируется с прошлым временем.

# Скриншот
![image](https://user-images.githubusercontent.com/103420483/179362665-8967fc7e-4ffb-44d3-910a-d50bce376e49.png)

# Окружение
* **Операционная система:** Windows 10 Домашняя
* **IDE:** IntelliJ IDEA Community Edition 2022.1.1
* **Java:** corretto-11.0.15

**Comment by Megalapka** [comment]
Fixed issue#4, addPlayTime
Исправила метод addPlayTime, время суммируется
