### ISSUE TITLE
Не суммируется общее количество времени всех игроков, проведённого за играми этого каталога

### ISSUE THREAD

**Issue by PershikovaEP** [Megalapka/javaqa-team-diplom#5]
# Описание
Не суммируется общее количество времени всех игроков, проведённого за играми этого каталога

# Локация дефекта
https://github.com/Megalapka/javaqa-team-diplom/blob/bd18eb18a316c1a098ccc18185b6aede417ee3d0/src/main/java/ru/netology/GameStore.java#L75-L77

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Megalapka/javaqa-team-diplom) в IDEA
1. Открыть класс GameStoreTest
1. Запустить тест shouldSumTime
1. Посмотреть в консоли

*Ожидаемый результат:* Тест пройден. Суммируется общее количество времени всех игроков, проведённого за играми этого каталога.
*Фактический результат:* Тест не пройден. Время не суммируется, выводится 0. 

# Скриншот
![image](https://user-images.githubusercontent.com/103420483/179363187-121a06ef-3e55-453e-95c3-cdbfaacdf39c.png)

# Окружение
* **Операционная система:** Windows 10 Домашняя
* **IDE:** IntelliJ IDEA Community Edition 2022.1.1
* **Java:** corretto-11.0.15

**Comment by Megalapka** [comment]
Fixed issue#5, fixed getSumPlayedTime()
Переписала код для метода getSumPlayedTime(). Время суммируется.
