### ISSUE TITLE
Не находит имя игрока с наибольшим временем равным 1. Вернулся null

### ISSUE THREAD

**Issue by PershikovaEP** [Megalapka/javaqa-team-diplom#6]
# Описание
Не находит имя игрока, который играл в игры этого каталога, с наибольшим временем равным 1. Вернулся null.
     
# Локация дефекта
https://github.com/Megalapka/javaqa-team-diplom/blob/bd18eb18a316c1a098ccc18185b6aede417ee3d0/src/main/java/ru/netology/GameStore.java#L58-L69

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Megalapka/javaqa-team-diplom) в IDEA
1. Открыть класс GameStoreTest
1. Запустить тест shouldFindPlayerWhenEqualTime
1. Посмотреть в консоли

*Ожидаемый результат:* Тест пройден. Найден игрок с наибольшим временем равным 1.
*Фактический результат:* Тест не пройден. Результат null

# Скриншот
![image](https://user-images.githubusercontent.com/103420483/179366658-dca2ec08-6df3-402c-899e-6ec101a0420c.png)

# Окружение
* **Операционная система:** Windows 10 Домашняя
* **IDE:** IntelliJ IDEA Community Edition 2022.1.1
* **Java:** corretto-11.0.15

**Comment by Megalapka** [comment]
Fixed bug in getMostPlayer(). Test shouldFindPlayerWhenEqualTime passed.
Исправлен код. Тест проходит.
