### ISSUE TITLE
При повторной установке игры время обнуляется

### ISSUE THREAD

**Issue by Megalapka** [Megalapka/javaqa-team-diplom#7]
# Описание
После того, как игрок уже сыграл в игру, а потом снова попытался установить эту игру, время сыгранное в неё обнуляется.

# Локация дефекта
https://github.com/Megalapka/javaqa-team-diplom/blob/bd18eb18a316c1a098ccc18185b6aede417ee3d0/src/main/java/ru/netology/Player.java#L24-L26

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Megalapka/javaqa-team-diplom/blob/main/src/test/java/ru/netology/PlayerTest.java) в IDEA
1. Запустить тест shouldInstallGameTwiceWithoutReset
1. Посмотреть в консоли

*Ожидаемый результат:* Тест пройден.
*Фактический результат:* Тест провален. 

# Скриншот
![issue7](https://user-images.githubusercontent.com/103579821/179370518-d3a7f949-f50b-4f75-9620-d78d5babede9.jpg)

 # Окружение

* **Операционна система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA 2022.1.1 (Community Edition)
* **Java:** corretto-11

**Comment by PershikovaEP** [comment]
Баг исправлен. При повторной установке игры игровое время остается прежним
