### ISSUE TITLE
Метод mostPlayerByGenre не возвращает жанр, в который играли больше всего

### ISSUE THREAD

**Issue by Megalapka** [Megalapka/javaqa-team-diplom#8]
# Описание
При запуске метода mostPlayerByGenre всегда возвращается null

# Локация дефекта
https://github.com/Megalapka/javaqa-team-diplom/blob/d875d0daf164f275c379f025c76f9ac817fa72bd/src/main/java/ru/netology/Player.java#L57-L59

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Megalapka/javaqa-team-diplom/blob/main/src/test/java/ru/netology/PlayerTest.java) в IDEA
1. Запустить тест shouldReturnMostPlayedByGenre
1. Посмотреть в консоли

*Ожидаемый результат:* Тест пройден.
*Фактический результат:* Тест провален. 

# Скриншот
![issue8](https://user-images.githubusercontent.com/103579821/179370879-c7dc5129-d4b9-4d13-909a-cb3ffb0386fc.jpg)

 # Окружение

* **Операционна система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA 2022.1.1 (Community Edition)
* **Java:** corretto-11

**Comment by PershikovaEP** [comment]
Баг исправлен. Метод возвращает игру по жанру, в которую играли дольше всего
