### ISSUE TITLE
Не проверяется исключение, когда пытаются сыграть в неустановленную игру

### ISSUE THREAD

**Issue by Megalapka** [Megalapka/javaqa-team-diplom#9]
# Описание
При попытке сыграть в неустановленную игру, должно выкидываться исключение.

# Локация дефекта
https://github.com/Megalapka/javaqa-team-diplom/blob/d86c99cde55789af28728155abcc197a2fe83cca/src/main/java/ru/netology/Player.java#L41-L49

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Megalapka/javaqa-team-diplom/blob/main/src/test/java/ru/netology/PlayerTest.java) в IDEA
1. Запустить тест shouldExceptionForPlayWithoutInstallGame()
1. Посмотреть в консоли

*Ожидаемый результат:* Тест пройден.
*Фактический результат:* Тест провален. 

# Скриншот
![issue9](https://user-images.githubusercontent.com/103579821/179424178-5c0f5b3e-3c78-4b24-97fa-0c5c53655c30.jpg)

# Окружение

* **Операционна система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA 2022.1.1 (Community Edition)
* **Java:** corretto-11

**Comment by PershikovaEP** [comment]
Баг исправлен. Добавила исключение при попытке сыграть в неустановленную игру. Тест пройден.
